(rule (target "static.0.err.oracle") (mode fallback) (action (write-file "static.0.err.oracle" "")))
(rule (target "static.0.res.oracle") (mode fallback) (action (write-file "static.0.res.oracle" "")))
(rule (target "static_f.0.err.oracle") (mode fallback) (action (write-file "static_f.0.err.oracle" "")))
(rule (target "static_f.0.res.oracle") (mode fallback) (action (write-file "static_f.0.res.oracle" "")))

