(rule (target "funptr_f.0.err.oracle") (mode fallback) (action (write-file "funptr_f.0.err.oracle" "")))
(rule (target "funptr_f.0.res.oracle") (mode fallback) (action (write-file "funptr_f.0.res.oracle" "")))
(rule (target "funptr.0.err.oracle") (mode fallback) (action (write-file "funptr.0.err.oracle" "")))
(rule (target "funptr.0.res.oracle") (mode fallback) (action (write-file "funptr.0.res.oracle" "")))

