(rule (target "callable_f.0.err.oracle") (mode fallback) (action (write-file "callable_f.0.err.oracle" "")))
(rule (target "callable_f.0.res.oracle") (mode fallback) (action (write-file "callable_f.0.res.oracle" "")))
(rule (target "callable.0.err.oracle") (mode fallback) (action (write-file "callable.0.err.oracle" "")))
(rule (target "callable.0.res.oracle") (mode fallback) (action (write-file "callable.0.res.oracle" "")))

