(rule (target "entry_f.0.err.oracle") (mode fallback) (action (write-file "entry_f.0.err.oracle" "")))
(rule (target "entry_f.0.res.oracle") (mode fallback) (action (write-file "entry_f.0.res.oracle" "")))
(rule (target "entry.0.err.oracle") (mode fallback) (action (write-file "entry.0.err.oracle" "")))
(rule (target "entry.0.res.oracle") (mode fallback) (action (write-file "entry.0.res.oracle" "")))

