let help_msg = "Plugin for varifying non-functional requirements"

module Self = Plugin.Register
  (struct
    let name = "vernfr"
    let shortname = "nfr"
    let help = help_msg
  end)

module Enabled = Self.False
(struct
  let option_name = "-vernfr"
  let help = "when on (off by default), " ^ help_msg
end)


module NfrLogFile = Self.String
(struct
  let option_name = "-nfr-logfile"
  let default = "nfr-log.txt"
  let arg_name = "log-file"
  let help = "File path to log file, which keeps output generated by API calls to, e.g., Eva" 
end)





module ISpecFile = Self.String
(struct
  let option_name = "-nfr-ispec"
  let default = ""
  let arg_name = "ispec-file"
  let help = "File path to interface file" 
end)


module CheckTypedefs = Self.False
(struct
  let option_name = "-nfr-typedefs"
  let help = "when on (off by default), emits a warning if a 'raw' type is used instead of a typedef, whenever a typedef exists" 
end)

module CheckStatic = Self.False
(struct
  let option_name = "-nfr-static-vars"
  let help = "when on (off by default), emits a warning if a global variable does not have static storage" 
end)

module CheckOnlyEntries = Self.False
(struct
  let option_name = "-nfr-only-entries"
  let help = "when on (off by default), emits a warning if function is declared that is not in the \
    list of entry-point functions in the specification. This option SHOULD ALWAYS be used in combination with the \
    frama-c kernel option '-keep-unused-functions all'" 
end)

module CheckCalls = Self.False
(struct
  let option_name = "-nfr-check-calls"
  let help = "when on (off by default), emits a warning if any external function \
    call is to a function not in the whitelist in the specification \
    (does not emit warnings for calls to local functions (with static storage))" 
end)

module CheckFunPtrs = Self.False
(struct
  let option_name = "-nfr-fun-ptrs"
  let help = "when on (off by default), emits a warning if any function call is a call \
    to a function pointer. Verification is at call sites." 
end)

module CheckNoDefs = Self.False
(struct
  let option_name = "-nfr-no-fun-defs"
  let help = "when on (off by default), emits a warning if any function is defined in an included h-file" 
end)

module ChecNoPtrArith = Self.False
(struct
  let option_name = "-nfr-ptr-arith"
  let help = "when on (off by default), emits a warning if any pointer arithmetic is detected" 
end)

module CheckProperInit = Self.False
(struct 
  let option_name = "-nfr-proper-init"
  let help = "when on (off by defualt), emits a warning if any global variable is used before being explicilty initialised"
end)


module CheckEntriesDeclared = Self.False 
(struct 
  let option_name = "-nfr-all-entries-declared"
  let help = "when on (off by defualt), emits a warning if not all entrypoints\
     in the ispec file are declared\
     (intended to be used for a header file)"
end)

module CheckEntriesDefined = Self.False 
(struct 
  let option_name = "-nfr-all-entries-defined"
  let help = "when on (off by defualt), emits a warning if not all entrypoints\
     in the ispec file are defined\
     (intended to be used for a C file)"
end)

module CheckPtrLiterals = Self.False 
(struct 
  let option_name = "-nfr-check-ptr-literals"
  let help = "when on (off by defualt), emits a warning if a pointer literal is detected \
    , which is defined as a cast from a int literal to a pointer"
end)



module CheckAll = Self.False
(struct
  let option_name = "-nfr-all"
  let help = "when on (off by default), runs all nfr checks by vernfr" 
end)